In [2]:
import numpy as np

In [3]:
# Question 1
# Defining the given matrix A
A = np.array([
  [1,2,3,4,5,6],
  [-7,-8,-9,-10,-11,-12],
  [13,14,15,16,17,18],
  [-1,-2,-3,-4,-5,-6],
  [7,8,9,10,11,12],
  [-13,-14,-15,-16,-17,-18]
])
A[:,:] = A[:,-1::-1] # Accessing all the rows and their entries and setting them equal to their corresponding reverse.
A[1::3,:] = -(A[1::3,:]) # Multiplying by negative one to row number two and five and setting them equal to corresponding rows.
print(A)

[[  6   5   4   3   2   1]
 [ 12  11  10   9   8   7]
 [ 18  17  16  15  14  13]
 [ -6  -5  -4  -3  -2  -1]
 [-12 -11 -10  -9  -8  -7]
 [-18 -17 -16 -15 -14 -13]]


In [4]:
# Question 2
def grid2D(a=-2,b=2,c=-4,d=4,n=10,m=10):
    
    dx = (b-a)/n
    dy = (d-c)/m
    x = np.array([a + i*dx for i in range(n+1)]) # creating array of x points in x direction with a space of dx
    y = np.array([c + i*dy for i in range(m+1)]) # creating array of y points in y direction with a space of dy.
    X = np.zeros((n+1,n+1)) # creating array for collecting x coordinates of intersection points.
    Y = np.zeros((m+1,m+1)) # creating array for collecting y coordinates of intersection points.
    for i in range(len(y)):
        #X[i] = np.array([x for x in x]) # putting x-coordinates of intersecting points in X.
        X[i] = x
        Y[i] = y[i] * np.ones(len(x)) # putting y-coordinates of intersecting points in Y.
    return(X,Y)

In [7]:
# Question 3
# defining given finction.
def f(x,y):
    return(np.exp(x**2 + y**2))
X,Y = grid2D() # setting X and Y to return values of grid2D function.
z = f(X,Y) # evaluating function on X and Y arrays.
print(Y)

[[-4.  -4.  -4.  -4.  -4.  -4.  -4.  -4.  -4.  -4.  -4. ]
 [-3.2 -3.2 -3.2 -3.2 -3.2 -3.2 -3.2 -3.2 -3.2 -3.2 -3.2]
 [-2.4 -2.4 -2.4 -2.4 -2.4 -2.4 -2.4 -2.4 -2.4 -2.4 -2.4]
 [-1.6 -1.6 -1.6 -1.6 -1.6 -1.6 -1.6 -1.6 -1.6 -1.6 -1.6]
 [-0.8 -0.8 -0.8 -0.8 -0.8 -0.8 -0.8 -0.8 -0.8 -0.8 -0.8]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8  0.8]
 [ 1.6  1.6  1.6  1.6  1.6  1.6  1.6  1.6  1.6  1.6  1.6]
 [ 2.4  2.4  2.4  2.4  2.4  2.4  2.4  2.4  2.4  2.4  2.4]
 [ 3.2  3.2  3.2  3.2  3.2  3.2  3.2  3.2  3.2  3.2  3.2]
 [ 4.   4.   4.   4.   4.   4.   4.   4.   4.   4.   4. ]]
